# Generated by Django 3.1.7 on 2021-03-24 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crmautomation', '0002_batch_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.IntegerField()),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('admission_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crmautomation.admissions')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('followup_date', models.DateField()),
                ('status', models.CharField(choices=[('admited', 'admited'), ('not admited', 'not admited')], max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crmautomation.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crmautomation.course')),
            ],
        ),
        migrations.AddField(
            model_name='admissions',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crmautomation.enquiry'),
        ),
    ]
