# Generated by Django 3.1.7 on 2021-03-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='eid',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
