# Generated by Django 3.1.7 on 2021-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0002_auto_20210330_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='admission_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='eid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
