# Generated by Django 3.1.7 on 2021-03-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0006_auto_20210331_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='batch_code',
            field=models.CharField(max_length=20),
        ),
    ]
