# Generated by Django 3.1.7 on 2021-04-03 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0007_auto_20210331_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 3)),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.enquiry', unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 3)),
        ),
    ]
