# Generated by Django 3.1.7 on 2021-04-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0009_auto_20210403_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.enquiry', unique=True),
        ),
    ]
