# Generated by Django 3.1.7 on 2021-04-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0010_auto_20210403_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissions',
            old_name='eid',
            new_name='enqid',
        ),
    ]
