# Generated by Django 3.1.7 on 2021-04-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0012_auto_20210403_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='batch_code',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='app_crm.batch'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admission_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.admissions', unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.enquiry', unique=True),
        ),
    ]
