# Generated by Django 3.1.7 on 2021-04-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0014_auto_20210403_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='batch_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.batch'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.enquiry'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admission_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.admissions'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_crm.enquiry'),
        ),
    ]
