# Generated by Django 3.1.7 on 2021-04-04 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0015_auto_20210403_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='batch_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 4)),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='eid',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admission_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 4)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='eid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
