# Generated by Django 3.1.7 on 2021-04-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0016_auto_20210404_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='batch_code',
            field=models.CharField(max_length=20),
        ),
    ]
